/*
*Project Euler (https://projecteuler.net/) Probelm 2:
*Author: Jonathan Piza
*Problem : Each new term in the Fibonacci sequence is generated by *adding the previous two terms. By starting with 1 and 2, *the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, *89, ...
*By considering the terms in the Fibonacci sequence whose *values do not exceed four million, find the sum of the *even-valued terms.
*/

sum = 0;
for(i = 11; i>0; i--){
  x = fibonacci(i); 
  if(x%2 == 0){
    sum += x;
  }
}
console.log("Sum of even values is " + sum);


//The recursive and pompus way to get the fibonacci sequence
function fibonacci(n)  {
    if(n == 0){
      return 0;
    }
    else if(n == 1){
      return 1;
    }
   else{
     return fibonacci(n - 1) + fibonacci(n - 2);
   }
}
